class Config:
    def __init__(self,
                 env_name='CartPole-v1',
                 use_prioritization=False,
                 use_atari=False,
                 load_checkpoint=False,
                 evaluate=False,
                 use_double=False,
                 use_dueling=False,
                 clip_reward=False,
                 n_threads=4,
                 memory_capacity=100_000,
                 batch_size=64,
                 alpha=0.5,
                 beta=0.5,
                 learner_device='cuda:0',
                 memory_device='cpu',
                 actor_device='cpu',
                 action_space='discrete',
                 n_actions=1,
                 learner_lr=1e-4,
                 target_replace_interval=1000,
                 warmup=0,
                 total_time=None,
                 n_step=1,
                 n_batches_to_store=1,
                 n_batches_to_sample=1,
                 actor_lr=1e-4,
                 critic_lr=1e-4,
                 actor_dims=[400, 300],
                 critic_dims=[400, 300]):
        self.env_name = env_name
        self.use_prioritization = use_prioritization
        self.use_atari = use_atari
        self.load_checkpoint = load_checkpoint
        self.evaluate = evaluate
        self.use_double = use_double
        self.use_dueling = use_dueling
        self.clip_reward = clip_reward
        self.n_threads = n_threads
        self.memory_capacity = memory_capacity
        self.batch_size = batch_size
        self.alpha = alpha
        self.beta = beta
        self.learner_device = learner_device
        self.memory_device = memory_device
        self.actor_device = actor_device
        self.action_space = action_space
        self.n_actions = n_actions
        self.learner_lr = learner_lr
        self.target_replace_interval = target_replace_interval
        self.warmup = warmup
        self.total_time = total_time
        self.n_step = n_step
        self.n_batches_to_store = n_batches_to_store
        self.n_batches_to_sample = n_batches_to_sample
        self.actor_lr = actor_lr
        self.critic_lr = critic_lr
        self.actor_dims = actor_dims
        self.critic_dims = critic_dims
